### ISSUE TITLE
Users can send but cannot receive stereo audio in Chrome, it is doing a mixdown of the received stereo signal to mono. Am I missing something?

### ISSUE THREAD

**Issue by pierreaa** [igniterealtime/openfire-pade-plugin#246]
I've been running the Pade plugin for a few months now. I am a musician / audio engineer. My collegues and I have been using Pade to work on music project and thanks to Dele Olajide's awesome work and contribution, we have been able to write music and work on studio mixes from our respective homes through Openfire, Pade, the JVB video bridge on a Debian Linux server. We are using Pade for Webcam shares, exchange files and send HD audio. With the pandemic situation, it's been a blessing.

I've been looking all around to find out why we cannot receive stereo audio in Chrome but we are able to send a stereo signal. There are tons of topics in forums everywhere about WebRTC and Chrome that talks about this issue, but since the stereo option is included in Pade's Chrome extension, I am seriously wondering if I am missing something. The Debian server has Opus installed. The host of the music session is sending a stereo mix of the music and his microphone through Chrome but the other users have to use Firefox to get the stereo audio signal. Chrome is doing a mixdown of the received stereo audio to mono. Is it possible to correct this on the server side? On the browser itself? I would greatly appreciate if someone could point me in the right direction! Dele, if you read this, a million thanks for this majestic work! :-D

**Comment by damencho** [comment]
There are properties you can pass to jitsi-meet, but some of them do not work in p2p mode, but only when using jvb. I'm not familiar with Pade and how that can work with it, but just wanted to point to the options: 
https://community.jitsi.org/t/jitsi-meet-for-music-teaching/90797/3?u=damencho

**Comment by deleolajide** [comment]
> Dele, if you read this, a million thanks for this majestic work! :-D

Thanks for the kind words, but the Pàdé project at ignite-real-time is just standing on the shoulders of the Jitsi Project

I did do a blog about using Pàdé for music collaboration after adding the stereo configuration setting. See
https://discourse.igniterealtime.org/t/openfire-meetings-for-music-collaboration/88529

The implementation is setting the Jitsi-Meet configuration properties as explained in post by @damencho 
I have not used it in a while and my code may need to be updated.  I will have a look as soon as as I get a free moment.

**Comment by gjaekel** [comment]
> The host of the music session is sending a stereo mix of the music and his microphone through Chrome but the other users have to use Firefox to get the stereo audio signal. 
For me, this sounds like a problem at the client side: If stereo is working with FF, but not with Chrome using the same Jitsi session with a stereo sourcing participant, the it's really implausible (but possible) that this is caused by the bridge.

With this new JVB2 and its stat/debug endpoint, it's possible to get comprehensive connection state information for each session and participants. @damencho will evaluate it with ease, but also we may find differences.

**Comment by pierreaa** [comment]
Thank you guys!! :-D Wow, I did not expect to get a response that fast!! 

Dele, I read the blog post a while ago. Our goal is not to jam together in real time, we write / produce and mix music, the audio latency caused by webcam sharing etc. is not an issue, only the stereo that is mixdown to mono in Chrome. We are used to work with plugins in digital audio workstations that induce latency and visuals that lags a little. We use an independant remote desktop / screenshare at the same time as well to work within the DAW. We tried Chrome on different machines, MacOS, Windows and could not figure it out... , I am definelty missing something. 

Damencho, I read quite a few of your posts about Jitsi, I have a standalone Jitsi installed on a CentOS server also. We have disabled p2p to help the HD audio / video sharing stability for Pade / Openfire. We use a Coturn server for the stun / turn signaling. I will definitely check these links! Thanks again!

**Comment by gjaekel** [comment]
> I'm not familiar with Pade and how that can work with it ...

@damencho Think _Pàdé_ (or more exact, it's component _OFmeet_) just as the enhanced _Jitsi Meet_ Web client. It will provide a bunch of additional features and tweaks. This is technical done by hooking a custom script by the upstream code and patching a few little things in the app.bundle.js. It's full "downward" compatible; with no problems you may use an upstream _Jitsi Meet_ App to join a meeting on an _OpenFire_ XMPP platform with the `Pàdé` plugin. Here we also run the vanilla components like JiCoFo and JVB(2) but use _OpenFire_ as the XMPP and Websocket frontend.

Said that, your hints are usable. Because OpenFire and its Plugins provide an HTML Admin UI, and the playout of `config.js` and `interfrace_config.js` is calculated from an internal registry, we have to check that it is up-to-date what is passed when the Admin checkmarks "provide stereo".

**Comment by gjaekel** [comment]
> Thank you guys!! :-D Wow, I did not expect to get a response that fast!!

@pierreaa It's rather cold outside :)

**Comment by gjaekel** [comment]
May you please cross-verify using https://appr.tc/r/mystereotestroom?stereo=true&audio=echoCancellation=false . (This taken from https://bugs.chromium.org/p/chromium/issues/detail?id=818180)

**Comment by pierreaa** [comment]
gjaekel! It is! Haha ;-) Winter time in Montreal Canada here, so it's cold all the way! Thank you for your help, it's greatly appreciated!

**Comment by gjaekel** [comment]
Great! I have the imagination of folk music at a chimney. This is in and in panacolor and stereo, of course.

Here, in Germany, we have some few centimeters of snow this weekend leading to the typical chaos. :)

**Comment by gjaekel** [comment]
What exact version of Chrome you're using? (Issue 8133: OPUS stereo audio over RTP is muxed to mono https://bugs.chromium.org/p/webrtc/issues/detail?id=8133)

**Comment by pierreaa** [comment]
gjaekel, I did the test with the current version of Chrome, the echoCancellation was not disabled by "echoCancellation=false" and the noise suppressor was also on so the music became noise, could not really tell if it was stereo. Haha ;-) I've seen this post about a week ago on bugs.chromium.org and installed Chrome 89 to test it, it was still mono on MacOS, same on Windows 10. I am planning on trying Chrome 90 also...

**Comment by pierreaa** [comment]
Hey gjaekel, earlier you mentioned that config.js and interface_config.js was calculated from an internal registry, what exactly do you mean? There is custom_config.js and a few other js files in Pade that, if I am not mistaken, overwrites the Jitsi config.js and interface_config.js and also options in the Openfire Pade plugins that are stored in the Openfire db and in the user's Chrome Pade extension. Is this what you are talking about?

**Comment by gjaekel** [comment]
TLTR: Yes. This was mainly for @damencho to explain the concepts of OFMeet:  

On a vanilla Jitsi installation, the files `config.js` and `interface_config.js` (that are pulled by the WebClient to config itsef), are delivered by a Ngix webserver as a static resource. Here, one have to edit this files at the server.

On OFMeet, this files are dynamical generated by two correspoing Java servlets (https://github.com/igniterealtime/openfire-pade-plugin/blob/master/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/ConfigServlet.java, https://github.com/igniterealtime/openfire-pade-plugin/blob/master/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/InterfaceConfigServlet.java) on request.
https://github.com/igniterealtime/openfire-pade-plugin/blob/79759d539a03e63a20985bcc504b64ff3ae32563/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/ConfigServlet.java#L313-L323

**Comment by gjaekel** [comment]
> gjaekel, I did the test [...] so the music became noise

As I was still idling at the URL, suddenly I heard some heavy distorted music. And as I switch to this tab, there was a video showing a working person on a office chair and some music instruments in the background -- this was probably you?!? Sorry, I have a cam at this workstation at the moment ...

**Comment by pierreaa** [comment]
Yes, it was me. I didn't stick around because I wanted to connect to this session a second time through a Windows laptop to check out if I would receive stereo music but the test is only for 2 persons, I guess in a peer to peer situation. I simply created a different room afterward. I was playing a 1978 Van Halen song because it's just obvious if the sound is mono since the Eddy's guitar is mixed on the left side only. This was the heavy distorted music! ;-) 

Thank you for the tip! Here is what I got mostly related to audio configuration:

  "disableNS": true,
  "enableLipSync": false,
  "opusMaxAverageBitrate": 510000,
  "disableAP": true,
  "disableAEC": true,
  "stereo": true,
  "disableAudioLevels": true,
  "enableNoAudioDetection": true,
  "disableHPF": true,
  "enableNoisyMicDetection": true,
  "disableAGC": true, 
   "useRtcpMux": true,

If I understood you right, some of the configs cannot be changed on my server since they are dynamical generated from the Github project Java servlets on request? Also, I am not sure what is  "useRtcpMux": true, is it that RTP is muxed to mono like stated in https://bugs.chromium.org/p/webrtc/issues/detail?id=8133?

**Comment by pierreaa** [comment]
Sorry about this,  "useRtcpMux" is for single-port multiplexing, nothing to do with audio.

**Comment by gjaekel** [comment]
> Sorry about this, "useRtcpMux" is for single-port multiplexing, nothing to do with audio.

No problem!

> If I understood you right, some of the configs cannot be changed on my server.

Yes, but that's on Github is just the Java source file. Java is a compiled language and the binaries are inside the plugin can't be changed as easy as an browser-interpreted javascript file. Instead, you have to go a complete compile-package-install cycle in most cases. Said that, there's a "developer override": On the server, you may add lines to `.../plugins/pade/classes/jitsi-meet/config_custom.js` in terms of
```
config.disableNS = true;
interfaceConfig.foo = bar;
```
This file is also read by the client browser "at the right time" and you may try out things here.

> I was playing a 1978 Van Halen song because it's just obvious if the sound is mono since the Eddy's guitar is mixed on the left side only.
A good testcase! I remember some old Motown songs with complete left/right separation, too.

**Comment by pierreaa** [comment]
I will add a few config changes to config_custom.js as you mentioned. Thank you for your help gjaekel, I've been reading and searching for a solution for quite a while so no worries, a few days / a week is nothing! ;-)

**Comment by gjaekel** [comment]
If you're able to work out some changes, we'll go to implement it inside the server side code.

**Comment by gjaekel** [comment]
OK to close here. I'm in contact to @pierreaa . 

I already tried to reproduce this, but on Linux, there don't seem to be a audio loopback source to be used as an audio input device out of the box. The feature "share audio" as an option for the browsers screenshare facility is available at Chromium, but also seems to work just "mono". Googling the web there might be a "webrtc mono issue" on Crome

**Comment by gjaekel** [comment]
I was able to transport stereo from an arbitrary application from _Src_ to _Dst_:

#### Transmitting System Sound instead of Mic Sound:

* On system _Src_, using Linux `pavucontrol`, at the _Recording_ tab I switched the input running chrome client window representing the conference from the Mic source to the source "Monitor of _System's default Audio Sink_". 


#### Transmitting Stereo
 * (re)join *both*,  the clients _Src_ *and* _Dst_ the with the URL-suffix `#config.stereo=true`

 This will made the current audio on _Src_ used as input for the Jitsi Client and will transmit it to _Dst_.

**Comment by pierreaa** [comment]
Thank you so much gjaekel for the heads up, it works!! :-D I tried this many times, this time it worked!

**Comment by gjaekel** [comment]
I'm sorry for the delay. I lost it a bit because I was busy with other tracks. But this days, to support an upcoming internal event, I was forced to deal with this.

Maybe in the meanwhile, something have changed upstream, e.g. with the latest changes in the WebClient. What we probably miss those days was that on have to apply the **stereo option** at the **destination** participant(s), too! 

Applying this on the *source*, it will enhance the input, i.e. send two channels with a highter bandwith instead of a mono mixdown and it also seems include disabling audio processing (like with `#config.disableAP=true`).

This will already rise the audio quality at the destination side, but enabling stereo at his end is also need to use the stereo signal.

Notice: The stereo option might be enabled in general at the Admin UI; this will server the participants webclients with the appropriate options set. But with the URL suffixes, this might be applied to single conferences.

**Comment by gjaekel** [comment]
Notice: Using current FireFox-88.0.1 at the destination side, the explicit enabling of stereo isn't required.
