### ISSUE TITLE
JitsiJvbWrapper - getConferenceStats Connection refused

### ISSUE THREAD

**Issue by riess82** [igniterealtime/openfire-pade-plugin#249]
This is my second attempt at getting pade plugin to work in openfire.

I gave up last time trying to set everything up after having problems with routing the video across NAT, anyway...

Now i wanted to try again and noticed that the videochat didnt work at all.
So i did the usual, updated openfire (to 4.6.2), updated pade by a manual upload to 1.3.1 and now I see, that nothing of the pade is really working. I DID upgrade the server OS to Ubuntu 20.04 between the last try and now.

Focus and jvb users are offline (using Active Directory to authenticate, checked for bad password logins, none. I can login to openfire through AD, so that part should be fine).

Stdoutt.log shows an error every time I open the Pade settings in the gui:
"ERROR org.jivesoftware.openfire.plugin.ofmeet.JitsiJvbWrapper - getConferenceStats 192.168.22.3
java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)"

The mentioned IP is the server Ip on which the whole openfire server is running. The server has 2 IPs but openfire is only listening on that one.

The server is behind a firewall and has iptables installed as well. No dropped packets that I noticed though.

Please help. I feel like it might be some small detail that I am missing. Or maybe i destroyed the whole config with all my messing around.

Best regards,
M

**Comment by deleolajide** [comment]
I think you might need @gjaekel  to help you with this when he is free

**Comment by gjaekel** [comment]
@riess82 What's your location and/or timezone, please? Will need about 1h for other work. I hope this is feasible to you.

**Comment by riess82** [comment]
wow, what a fast reply. I'm not in any particular hurry, but I am UTC+1 and except for some minutes offline i will be able to give fast answers in the next few hours.

**Comment by gjaekel** [comment]
Maybe we can even (OF)meet to a hands-on session lateron. May you tell me your email?

**Comment by riess82** [comment]
I will send you a short email.

**Comment by gjaekel** [comment]
It's OK to close here: I'm in steady contact to @riess82. Up to now, he starts the third attempt to install Openfire and Pàdé from the scratch and stepped in a couple of problems. Because first goal is to get things running, we don't analyze the core reasons for the problems at the moment. 

Last state is that the JVM's are running and do log the start. The remaining problem is that's still some trouble to build up a conference session.

"Highlights" of issues
* spawned by OpenFire, the external JVM don't came up with a "main class not found". But started on the shell with the command line copies from the log, they start.
* The default values for the additional JVM option "disappear" after first start; the seems to be overridden by an empty string.
* The values entered for additional JVM options in the Admin GUI are silent cut down to a certain length (which is to small) and may corrupt the "commandline".
