### ISSUE TITLE
Default component values not used

### ISSUE THREAD

**Issue by MagicD3VIL** [igniterealtime/openfire-pade-plugin#272]
In the clean installation of the Openfire, once I restarted the Pade plugin once, the Jitsi VideoBridge and Jitsi Colibri Focus components always reported as offline. I could not find anything in the log and I tried reinstalling and reverting to default values multiple times and always after restarting Openfire or Pade the components would not start and reported with the red icon.

After few hours I tried filling the Java Virtual Machine (JVM) Settings section in the Settings category **with the exact default values that were already there** as an example (aka `-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp`).

I was really mad because after filling these fields up with the example/default values **that were basically already there** the components started up after restarting the plugin. Why was Pade not using the default/example values (`-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp`) from the start? The UI makes this portion of settings misleading and needs to be fixed.

Just to be sure I tried to remove the values from the fields again to the default state where the same text is gray and the components did not start without me manually filling these fields with the exact same text.

**Comment by deleolajide** [comment]
The issue is here 

https://github.com/igniterealtime/openfire-pade-plugin/blob/c12ce2bc610e87b96f38d7500490a22987b0831e/pade/src/web/ofmeet-settings.jsp#L309

The default values are actually empty instead of **-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp**

https://github.com/igniterealtime/openfire-pade-plugin/blob/c12ce2bc610e87b96f38d7500490a22987b0831e/ofmeet/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L186

.

> Why was Pade not using the default/example values (-Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp) from the start? 

That is an example and the recomeneded values for a production server. It is not the default value

**Comment by gjaekel** [comment]
From my consulting to M. Riess, I notice and confirm that the external JVMs may don't start with it's own default values, i.e. with an empty options string. That's one point of our backlog.
