### ISSUE TITLE
Suggestions on being able to scale the Video Conferencing.

### ISSUE THREAD

**Issue by 0bhat** [igniterealtime/openfire-pade-plugin#281]
Is the current system able to handle 1000 users concurrently in different rooms.
Can I use Openfire clustering for this?

**Comment by gjaekel** [comment]
This depends on your understanding of "system": To my knowledge, the software isn't limited in principle. But you have to deal with the limits introduced by your hardware.

There's a read big non-commerical plattform in Germany by the Freifunkt e.V. (https://meet.ffmuc.net). They don't use OpenFire but Progidy the products as prefered by Jitsi.org. In peak, the handle more than 5000 participants. They use about >=20 Containers with Video bridges because the leased hardware is limited to run about 100-200 participants on each JVB node.

**Comment by 0bhat** [comment]
Can I try using Openfire Clustering plugin to try to achieve the HA?

**Comment by gjaekel** [comment]
I don't have any experience with HA-OpenFire. Said that, the configuration of the JVB2's needs to be expanded to build a cluster. This will require support by the Plugin to generate the config files.

**Comment by gjaekel** [comment]
To get an idea of the requirements, you may look at https://stats.ffmuc.net/
