### ISSUE TITLE
AdminUI force to provide JVM options for JiGaSi even if disabled

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#302]
With some latest fixes, one is forced to provide runtime options for the external JVM used by *JiCoFo*, *JVB2* and *JiGaSi*.

But in spite of the first two, running *JiGaSi* is optional and probably kept disabled in the most cases.

Don't force to provide values for *JiGaSi* as long as it is disabled.

**Comment by deleolajide** [comment]
If you are configuring JVM options for JVB and Jicofo, you might as well do Jigasi because you are in that mindset. It is really no effort even you have no plan to use Jigasi. For someone who does not use Jigasi, I can see that pont of view.

Later on if and when you enable Jigasi, you would be doing it elsewhere, completely forgetting that JVM options have not been set. For someone who would be using Jigasi, I can also see this point of view.

**Comment by gjaekel** [comment]
I also see your point. What's about to add a warning (or even a blocker) about missing JVM options on the JiGaSi page if someone try to enable it?

**Comment by gjaekel** [comment]
Implemented this in #304 .
