### ISSUE TITLE
Missing Pade plugin Title and gibberish details

### ISSUE THREAD

**Issue by blckhwk** [igniterealtime/openfire-pade-plugin#356]
![pade](https://user-images.githubusercontent.com/7903090/121625974-1c6a2680-caa7-11eb-82a5-b5b5937464a2.png)

Here is the screenshot of the error I encountered. This happens after I updated from Pade plugin version 1.3.3 to 1.4.1

**Comment by gjaekel** [comment]
Thank you for the report.

What language do you have chosen for the Admin UI, please. And what's the Operating System?

You see the internal keys used for the language-specific translations as a fallback because it have failed. Do you see a file {{.../plugins/pade/i18n/pade_i18n.properties}} in your installation?

**Comment by blckhwk** [comment]
![image](https://user-images.githubusercontent.com/7903090/122182911-4b283880-cebd-11eb-89b3-6c84d7b49f21.png)

![image](https://user-images.githubusercontent.com/7903090/122183045-701cab80-cebd-11eb-97ab-dba808b5b139.png)

OS: Centos 8

I have this file "pade_i18n.properties"

![image](https://user-images.githubusercontent.com/7903090/122184913-45cbed80-cebf-11eb-96fc-3bb160364a22.png)

**Comment by gjaekel** [comment]
Thank you for the feedback. Sorry, but I don't have a real clue yet what's the technical reason for the issue. I remember that others have reported _empty_  titles after an upgrade, but I don't know about a key-ready solution.

Beside of this, the used Java version is **very** outdated. You should consider to switch to OpenJDK, the current one is *Java8u292*.

What other Plugins are installed: May you also list the directory (`ls -lah`) holding the plugins, i.e. one level up? 

You may try to stop OpenFire, remove all obvious related at `/var/tmp/`  and start again.

**Comment by blckhwk** [comment]
Thank you for the assistance gjaekel.

![image](https://user-images.githubusercontent.com/7903090/122191447-54b59e80-cec5-11eb-8100-d980df85f3a2.png)

I will upgrade the Java version later.

**Comment by gjaekel** [comment]
Gotcha! It's our mistake because there are no adequate warnings and/or instructions:

The **Pàdé** is a consolidated package, that **contain** other packages you still have installed: You **must** de-install the former separate packages `OFFocus`, `OFGaSi`, `OFMeet`.

Remove the `OF*` packages and restart OpenFire afterwards.

**Comment by blckhwk** [comment]
![image](https://user-images.githubusercontent.com/7903090/122319397-2a122700-cf53-11eb-85d1-400f409abe64.png)

Pade already updated. Thanks for your help @gjaekel.

**Comment by gjaekel** [comment]
From this picture, this means you can't see entries for the other **old** plugin's at the Admin UI. That's a broken state, because the Jetty server will "see" and use outdated files from directory trees that must not be existing anymore

* Stop OpenFire
* At the plugin directory, remove the old packages by OpenFire manually: `rm -r of*` and check by `ls -lah`. (Each JAR is the downloaded delivery unit. It is expanded by Openfire into the same-named directory tree and used from here. The expansion is controlled by the existence and timestamp of the rollout directory in relation to the JAR)
* Start OpenFire

This should do the job, IMHO.

_FYI: I can't continue here because I'll be on holiday until last days of month. Maybe @deleolajide can take over._

**Comment by blckhwk** [comment]
@gjaekel, thanks for your response.  I think the issue was partially solved, I just need to do the manual deletion of the plugin files from the openfire directory. Then this issue can be closed.  Thank you for your help @gjaekel.
