### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by SpiderChat** [igniterealtime/openfire-pade-plugin#361]
Any doc installations guide?

Thank you

**Comment by gjaekel** [comment]
At the moment, the `README.md` and some pages in the Wiki section, e.g https://github.com/igniterealtime/openfire-pade-plugin/wiki/OFmeet-Network-Scheme.

What information do you looking for? Do you already installed or used OpenFire, before?

**Comment by SpiderChat** [comment]
Oic, this for OpenFire? 

I think it is for Jitsi. Apologize for my misunderstanding.

**Comment by SpiderChat** [comment]
Any guide to install that?

Operating system: Linux - Ubuntu/debian
Need to install? 
1.
2
.3
etc

How to run?

How to connect?

**Comment by gjaekel** [comment]
For _OpenFire_: See https://www.igniterealtime.org/projects/openfire/documentation.jsp
For _Pàdé_: As written.

Please describe your available skills. In general, I don't recommend to operate an A/V-platform without adequate practice. Because it require some deeper general knowledge (operating system, networking, security) if you want to end up with a reliable, performant service.

The notorious lack of deep documentation for may open source projects is a known problem. But sorry, here I would tend to say: If you need a installation document in copy&paste-style, you'll will not be able to perform the adaption to your local requirements, the sizing and tuning and later, the operating and maintenance. In the other hand, I (we) will support you any "3rd level" issue by best effort. And you will get professional support from IniteRealtime and it's partners for sure.

If you like to discuss: Please also describe you use case for the A/V-Platform, the expected usage volume and the motivation to use a self-hosted installation.
