### ISSUE TITLE
pade audio/video conference call issue

### ISSUE THREAD

**Issue by paull25** [igniterealtime/openfire-pade-plugin#366]
Hey, hope you guys are doin' fine. I got a single OF 4.6.4 set-up with latest pade installed. Audio/video conference works great in a max of 10 participants, when I add more participants, the conference call crashes then participants will auto rejoin with poor audio quality. Maybe i am missing configuration here to fine tune the call experience? 

Thanks!

**Comment by gjaekel** [comment]
Dear @paull25,
thank you using _Openfire_ and the _Pàdé_ plugin. There seems to be a resource problem. May you please provide a "clean" log of the startup (stop openfire, rotate `all.log` an start again) and the ongoing join of participants to the conference -- if possible -- until the "crash"?

Maybe the Java heap of the JVMs are to small or you're out of files/sockets on your platform. Do you use Linux?

**Comment by paull25** [comment]
Hi @gjaekel ,

I appreciate that you look into my concern. I did configure OF 4.6.4 in a Linux 21.04 box with Java 11.0.11 and mysql 8.0.24.

[all.log](https://github.com/igniterealtime/openfire-pade-plugin/files/7147073/all.log)

Btw, is there a known limitation with the number of participants w/ both audio/video turned-on in a pade plugin conference call?

**Comment by paull25** [comment]
Hi @gjaekel ,

Thanks for your patience. Glad to hear OF with Pàdé plugin works great in action.

My apology since I am new to OF. I collected the logs based on below steps:
     - clear all the logs via OF gui
     - restart OF instance
     - fireup a test call and make all the  participants join until the call drop automatically which it did
     - i got the all.log from /usr/share/openfire/logs/
  
   I didn't configure anything in JVM and all is pretty much default. The box provide 4cores and 16gb in ram.
  
  This is the output of jps -lv
  ![image](https://user-images.githubusercontent.com/71937787/132944323-e8db7b91-3b1d-4409-8bdf-eaa1fe63055d.png)

**Comment by gjaekel** [comment]
For the output of `jps`, your JVMs for JiCoFo and JVB get 1GB Heap (`-Xmx`) and the JVM running OpenFire itself is unconfigured and should take 25% of the 16GB from that, i.e. 4GB.

Maybe the log was already rolled around because the current default of Openfire is still to roll by size? Then, this might be "to small" in comparisson to the heavy logging. I don't remember because I re-configured the `log4j2.xml` ancient times ago.

**Comment by gjaekel** [comment]
I study the log, again. It seems that you're loosing your participants because of "connectivity test" timeouts done by the JVB. The JVB then shut down the connections one by one. 

The A/V streams are using UDP.  Maybe the packets are dropped somewhere because of bottlenecks. Please tell me something about your network: Is this all local traffic? What's the bandwith of the interfaces and the backbone?

Maybe you're out of sockets? What's the file descriptor limit for your technical openfire user (`ulimit -a` for that user)?

**Comment by paull25** [comment]
Hi @gjaekel ,

Woahh, a mouthful of info, I need a breather! But hey, this is great and I really appreciate you giving deep technical info which you are always doing in this community.

Going back, you mentioned that "JVM running Openfire is unconfigured". How do I configure the JVM for Openfire? 
Reviewing these links to configure JVMs:
         https://discourse.igniterealtime.org/t/jvm-settings-and-debugging/49010
         https://discourse.igniterealtime.org/t/increasing-java-memory/49582/6

For logs, I did not included all the logs found in ${sys:openfireHome} which is pointing to /var/log/openfire and /usr/share/openfire/logs . Might be the log files are renamed xx.log-1 and so on respectively each time I cleared them out of the Openfire gui. Btw, thanks for sharing your rotating log technic, I am taking note of that.

I did not mention that I logged-in 10 test accounts to join the conference call in a single computer to replicate my issue. That served to be the timeout/disconnection/bottleneck you saw in the log that I provided.

Also, monitoring plugin reported a peak server traffic everytime I encounter the conference call issue. This points me in taking a look in tuning up as well my OS network stack as all is pretty much by default.

**Comment by gjaekel** [comment]
The first link about configuring the JVM offer a lot of suggestion and informations, but you have to be familiar with Java and the JVM to understand it in deep, i think :)
Where to add this options depend on your Openfire-starter. Because we do a lot with Java and because I'm using Gentoo with OpenRC as Init system, I do this by my own. The JVM options are somewhat sorted by "importance". The first choose a modern garbage collector what wasn't the default on Java-8. The next explicit configure the heap sizes and `-XX:MaxGCPauseMillis` advises the GC to aim a certain maximal "Stop World" time span. 

During certain times of (Full) Garbage Collection, a JVM have to suspend **all** threads and therefore will not process any data. For applications like the JVB, this must be avoided as much as possible because here the network buffers will be filled. Using GC1, a Full GC will be need very seldom on normal circumstances. But if the JVM run's near "out of heap", the GC will try to free long-unused objects on the main heap and just before a overflow, there is a forced full GC as the last resort.

It's a bit advantage, but you get very good life impressions of ongoing GC, if you use the _(J)VisualVM_ tool and it's _Visual GC_-plugin.

**Comment by gjaekel** [comment]
What's your country / timezone? To my experience, such an issue is hard to catch by post-mortem information. As an option, we may meet for a "debugging session" via your or my OpenMeeting. You may contact me via email mentioned in the Github profile in that case. We may use even shared _tmux_ session provided though ssh or the smart ttyd (https://github.com/tsl0922/ttyd).

**Comment by paull25** [comment]
Hi @gjaekel ,

Sorry in getting back this late as I was out for 4 days. Anyway, I was able to configure my OF box based on your provided settings, apparently this has no to little effect in my environment. The changes that I have made as are follows:

- JVB and Jicofo heap settings
- ulimit 
- IP stack 

![image](https://user-images.githubusercontent.com/71937787/133558117-bd271b3b-3616-4217-8381-8b9eaee875ae.png)


The network traffic in OF gui stats peaks high when I encounter the issue.
![image](https://user-images.githubusercontent.com/71937787/133559413-a181ae1f-66b5-4b9f-9d29-8d14fb0f6d6d.png)


This is my current OF environment. I have a single OF instance serving IM (spark client) and A/V conferencing (Pàdé) expecting 1000 users. Most users are accessing via VPN.

Are you running an OF cluster? To further troubleshoot, I am thinking to add more OF instances to split the network traffic/compute resource and check the perf from there. 

Thanks again @gjaekel !

**Comment by gjaekel** [comment]
Dear @paull25,
serving this number of user is a respectable usecase. No, I don't run a cluster and I don't know anybody (@deleolajide : Do you?). To my knowledge, clustering of OpenFire itself (i.e. the XMPP component) is well-introduced. But the Jitsi components (Conference Focus and Video Bridge) use their own protocols.

**Comment by gjaekel** [comment]
The file handle limit for your OpenFire user (at least, but probably for all) is a **lot** to low! Add something like
```
*		hard	nofile		64536
*		soft	nofile		64400
```
to `/etc/security/limits.conf` on servers for technical users. You may replace `*` (defining the default) by account names to assign individual limits.

**Comment by gjaekel** [comment]
Here some recent statistics of a day with two "real big" meetings. I myself participate the event at 13 o'clock, this was a lecture with 3 speakers and about 80 listeners. Most of the listeners had have Video muted, therefore this was a task to bridge about 20 to 80 Video streams.
![image](https://user-images.githubusercontent.com/19855721/133567949-0087ebd1-ab36-45fe-bd5c-86cb3bc03454.png)

To my knowledge, the "unit" of "JVB stress" is calibrated an typical "8Core cloud server". The peak at about corresponds well to the monitored CPU load, which peaks to 600%.

**Comment by paull25** [comment]
Hi @gjaekel ,

Again, thank you for your support. I have sent you an email to discuss further my current OF setup. 

Thanks again!

**Comment by deleolajide** [comment]
I am closing this issue. My advice is to force VP9 codec in Pade and reduce bandwidth. Otherwise, try clustering with multiple Openfire servers with multiple Jitsi Video-bridges and a single focus user.
